"use client";
import {useMemo,useState} from "react";import {motion} from "framer-motion";import {Check} from "lucide-react";

type Props={onComplete:(token:string)=>void};
const tiles=[
{id:'moon',mark:'☾',label:'달기와'},
{id:'sun',mark:'☀',label:'해기와'},
{id:'flower',mark:'✿',label:'꽃기와'},
{id:'star',mark:'✦',label:'별기와'},
];
const rounds=['flower','moon','star'];
export function GiwaGame({onComplete}:Props){const[round,setRound]=useState(0);const[wrong,setWrong]=useState('');const[loading,setLoading]=useState(false);const target=useMemo(()=>tiles.find(t=>t.id===rounds[round])!,[round]);async function choose(id:string){if(loading)return;if(id!==target.id){setWrong(id);setTimeout(()=>setWrong(''),400);return}if(round<rounds.length-1){setRound(v=>v+1);return}setLoading(true);try{const response=await fetch('/api/whitelist/assembly',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:true})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not unlock whitelist.');sessionStorage.setItem('tile_assembly_token',result.token);onComplete(result.token)}finally{setLoading(false)}}return <div className="grid gap-8 lg:grid-cols-[.78fr_1.22fr]"><div><p className="wl-kicker">STEP 01 · GIWA CHALLENGE</p><p lang="ko" className="mt-2 text-xs font-semibold text-white/55">기와 선택</p><h3 className="mt-5 text-3xl font-black tracking-[-.04em] text-white sm:text-4xl">Choose the right roof tile.</h3><p className="wl-muted mt-4 text-sm leading-6">Traditional Korean roofs are defined by their repeating giwa tiles. Match the requested symbol three times to open the whitelist form.</p><div className="mt-6 rounded-2xl border border-white/15 bg-black/20 p-5"><p className="text-[10px] font-bold tracking-[.18em] text-white/45">ROUND 0{round+1} / 03</p><div className="mt-4 flex items-center gap-4"><div className="flex h-16 w-24 items-end justify-center rounded-t-[60%] border border-[#d9c29a]/35 bg-[#3d4745] pb-3 text-3xl text-[#efd8a8] shadow-inner">{target.mark}</div><div><p className="text-xs font-bold text-white/45">FIND THIS GIWA</p><p lang="ko" className="mt-1 text-lg font-bold text-white">{target.label}</p></div></div></div></div><div className="grid grid-cols-2 gap-3">{tiles.map(tile=><motion.button key={tile.id} onClick={()=>choose(tile.id)} whileHover={{y:-3}} animate={wrong===tile.id?{x:[0,-6,6,-4,4,0]}:{}} className="focusable relative min-h-36 overflow-hidden rounded-2xl border border-white/15 bg-gradient-to-b from-[#59635f]/80 to-[#303734]/90 p-5 text-left shadow-lg transition hover:border-[#e7d2a5]/45"><div className="absolute inset-x-0 top-0 h-2 bg-repeating-linear-gradient"/><span className="block text-4xl text-[#efd8a8]">{tile.mark}</span><span lang="ko" className="mt-5 block text-sm font-bold text-white">{tile.label}</span><span className="mt-1 block text-[9px] font-bold tracking-[.16em] text-white/40">GIWA · ROOF TILE</span>{round>0&&rounds.slice(0,round).includes(tile.id)&&<Check className="absolute right-3 top-3 text-[#efd8a8]" size={20}/>}</motion.button>)}<div className="col-span-2 rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-xs font-semibold text-white/55">{loading?'화이트리스트를 여는 중…':'3 correct choices unlock the application.'}</div></div></div>}
