"use client";
import {useMemo,useState} from "react";import {motion} from "framer-motion";import {Check,RotateCcw,Sparkles} from "lucide-react";

type Props={onComplete:(token:string)=>void};
const tiles=[
{id:'moon',mark:'☾',label:'달기와',bg:'bg-blue'},
{id:'sun',mark:'☀',label:'해기와',bg:'bg-yellow'},
{id:'flower',mark:'✿',label:'꽃기와',bg:'bg-pink'},
{id:'star',mark:'✦',label:'별기와',bg:'bg-mint'},
];
const rounds=['flower','moon','star'];
export function GiwaGame({onComplete}:Props){const[round,setRound]=useState(0);const[wrong,setWrong]=useState('');const[loading,setLoading]=useState(false);const target=useMemo(()=>tiles.find(t=>t.id===rounds[round])!,[round]);async function choose(id:string){if(loading)return;if(id!==target.id){setWrong(id);setTimeout(()=>setWrong(''),450);return}if(round<rounds.length-1){setRound(v=>v+1);return}setLoading(true);try{const response=await fetch('/api/whitelist/assembly',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:true})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Could not unlock whitelist.');sessionStorage.setItem('tile_assembly_token',result.token);onComplete(result.token)}finally{setLoading(false)}}return <div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border-3 border-ink bg-blue/20 p-6"><span className="inline-flex items-center gap-2 rounded-full border-2 border-ink bg-yellow px-3 py-2 text-xs font-black"><Sparkles size={14}/> WL GAME · 기와 찾기</span><h3 className="mt-5 text-4xl font-black tracking-[-.05em]">Find the right GIWA.</h3><p className="mt-4 text-sm font-bold leading-6 text-steel">Match the requested Korean roof tile three times to unlock the whitelist form.</p><p lang="ko" className="mt-3 text-sm font-black">알맞은 기와를 골라 화이트리스트를 열어보세요!</p><div className="mt-7 rounded-2xl border-3 border-ink bg-white p-5 text-center shadow-sticker"><p className="text-[10px] font-black tracking-[.18em] text-steel">ROUND 0{round+1} / 03</p><p className="mt-2 text-sm font-black">FIND</p><div className={`mx-auto mt-3 flex h-20 w-20 items-center justify-center rounded-[50%_50%_20%_20%] border-3 border-ink ${target.bg} text-4xl font-black shadow-sticker`}>{target.mark}</div><p lang="ko" className="mt-3 text-xs font-black">{target.label}</p></div></div><div><div className="grid grid-cols-2 gap-4">{tiles.map(tile=><motion.button key={tile.id} onClick={()=>choose(tile.id)} whileHover={{y:-5,rotate:tile.id==='moon'?-2:2}} animate={wrong===tile.id?{x:[0,-8,8,-6,6,0]}:{}} className={`focusable relative min-h-40 rounded-[45%_45%_18%_18%] border-4 border-ink ${tile.bg} p-5 text-center shadow-sticker`}><span className="text-5xl font-black">{tile.mark}</span><span lang="ko" className="mt-3 block text-sm font-black">{tile.label}</span><span className="mt-1 block text-[10px] font-black text-steel">ROOF TILE</span>{round>0&&rounds.slice(0,round).includes(tile.id)&&<Check className="absolute right-3 top-3 rounded-full border-2 border-ink bg-white p-1" size={26}/>}</motion.button>)}</div><div className="mt-5 flex items-center justify-between rounded-xl border-2 border-ink bg-white px-4 py-3 text-xs font-black"><span>{loading?'UNLOCKING WL…':'3 correct tiles unlock the form'}</span><RotateCcw size={15}/></div></div></div>}
