"use client";
import { motion } from "framer-motion";
import { ArrowDownRight } from "lucide-react";

const metadata = [["TILE / 1111", "1111개의 조각"], ["KR / DIGITAL CULTURE", "디지털 문화"], ["GIWA DESTINATION", "네트워크 목적지"]];

export function Hero() {
  return <section id="top" className="mesh relative min-h-screen overflow-hidden border-b border-line"><div className="mx-auto grid min-h-screen max-w-[1400px] items-center gap-16 px-6 pb-16 pt-28 lg:grid-cols-[1.1fr_.9fr] lg:px-12"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7 }}><div className="mb-9 flex flex-wrap gap-x-7 gap-y-2">{metadata.map(([en, ko]) => <p key={en} className="font-mono text-[9px] tracking-[.15em] text-steel">{en} <span lang="ko" className="ml-1 text-slate-600">{ko}</span></p>)}</div><p className="eyebrow mb-8">COLLECTION PROTOCOL · <span lang="ko">컬렉션 프로토콜</span></p><h1 className="max-w-4xl text-6xl font-semibold leading-[.93] tracking-[-.06em] sm:text-8xl xl:text-[7.5rem]">1111 pieces.<br /><span className="text-steel">One bigger picture.</span></h1><p lang="ko" className="mt-5 text-xs tracking-[.18em] text-blue">1111개의 조각. 하나의 더 큰 그림.</p><p className="mt-8 max-w-xl text-base leading-7 text-steel">TILE is a 1,111-piece collection built around a simple idea: one piece may be small, but together they form something bigger.</p><p className="mt-4 text-sm text-blue">Built for the road to GIWA.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#whitelist" className="focusable bg-white px-6 py-4 text-xs font-bold uppercase tracking-widest text-ink transition hover:bg-blue">Enter TILE</a><a href="#collection" className="focusable border border-line px-6 py-4 text-xs uppercase tracking-widest transition hover:border-steel">Explore TILE</a></div></motion.div><HeroTiles /></div><div className="absolute bottom-8 right-8 flex items-center gap-3 font-mono text-[9px] text-steel">GRID / ACTIVE <ArrowDownRight size={18} /></div></section>;
}

function HeroTiles() {
  return <div aria-hidden="true" className="relative mx-auto aspect-square w-full max-w-[520px] border border-line p-3"><span className="absolute -right-px -top-7 font-mono text-[9px] text-steel">MODULAR FIELD / 07×07</span><div className="grid h-full grid-cols-7 gap-1.5">{Array.from({ length: 49 }, (_, index) => <motion.div key={index} initial={{ opacity: 0 }} animate={{ opacity: [.12 + ((index * 7) % 8) / 10, .42 + ((index * 3) % 5) / 10, .12 + ((index * 7) % 8) / 10] }} transition={{ delay: index * .018, duration: 5 + (index % 4), repeat: Infinity }} className={`relative border border-white/10 ${index === 24 ? "bg-blue/70" : "bg-slate-500/30"}`}>{index % 8 === 0 && <span className="absolute left-1 top-1 font-mono text-[6px] text-white/30">{String(index + 1).padStart(2, "0")}</span>}</motion.div>)}</div></div>;
}
