"use client";
import { motion } from "framer-motion";
import { ArrowDownRight, Sparkles } from "lucide-react";

export function Hero(){return <section id="top" className="mesh relative min-h-screen overflow-hidden border-b-4 border-ink"><KoreanWorld/><div className="relative z-10 mx-auto grid min-h-screen max-w-[1400px] items-center gap-10 px-6 pb-20 pt-28 lg:grid-cols-[1.08fr_.92fr] lg:px-12"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.6}}><div className="mb-6 inline-flex -rotate-2 items-center gap-2 rounded-full border-2 border-ink bg-yellow px-4 py-2 text-xs font-black shadow-sticker"><Sparkles size={15}/> 어서 와! WELCOME TO TILE</div><p className="mb-4 text-sm font-black tracking-[.22em] text-pink">1111 TILES · 하나의 큰 그림</p><h1 className="max-w-4xl text-6xl font-black leading-[.88] tracking-[-.07em] sm:text-8xl xl:text-[8.2rem]">ONE TILE<br/><span className="relative inline-block text-blue">AT A TIME.<span className="absolute -right-9 -top-4 rotate-12 text-4xl text-pink">✦</span></span></h1><p className="mt-7 max-w-xl text-lg font-bold leading-7">A playful 1,111-piece NFT collection inspired by Korean culture, tiles, and the road to GIWA.</p><p lang="ko" className="mt-2 font-bold text-steel">작은 조각들이 모여 하나의 이야기가 됩니다.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#whitelist" className="focusable -rotate-1 rounded-xl border-3 border-ink bg-pink px-7 py-4 text-sm font-black uppercase tracking-wider text-white shadow-sticker transition hover:rotate-1 hover:-translate-y-1">GET WHITELIST ✦</a><a href="#collection" className="focusable rotate-1 rounded-xl border-3 border-ink bg-white px-7 py-4 text-sm font-black uppercase tracking-wider shadow-sticker transition hover:-rotate-1 hover:-translate-y-1">MEET THE 1111</a></div><div className="mt-10 flex flex-wrap gap-3 text-xs font-black"><span className="rounded-full border-2 border-ink bg-mint px-4 py-2">✓ ASSEMBLE</span><span className="rounded-full border-2 border-ink bg-white px-4 py-2">✓ APPLY</span><span className="rounded-full border-2 border-ink bg-yellow px-4 py-2">✓ POST</span><span className="rounded-full border-2 border-ink bg-blue px-4 py-2">✓ VERIFY</span></div></motion.div><MysteryTiles/></div><div className="absolute bottom-5 left-1/2 z-10 hidden -translate-x-1/2 items-center gap-2 rounded-full border-2 border-ink bg-white px-4 py-2 text-xs font-black md:flex">SCROLL TO PLAY <ArrowDownRight size={16}/></div></section>}

function KoreanWorld(){return <div className="hanok-sky" aria-hidden="true"><div className="noise"/><div className="sun"/><div className="cloud cloud-a"/><div className="cloud cloud-b"/><div className="hanok hanok-left"><div className="roof"/><div className="house"/></div><div className="hanok hanok-right"><div className="roof"/><div className="house"/></div><motion.div className="doodle-tile left-[45%] top-[16%] h-12 w-12 bg-pink" animate={{rotate:[-8,8,-8],y:[0,-8,0]}} transition={{duration:4,repeat:Infinity}}/><motion.div className="doodle-tile right-[7%] top-[48%] h-16 w-16 bg-mint" animate={{rotate:[7,-7,7],y:[0,10,0]}} transition={{duration:5,repeat:Infinity}}/></div>}

function MysteryTiles(){const colors=['bg-pink','bg-blue','bg-yellow','bg-mint','bg-white'];return <div className="relative mx-auto w-full max-w-[510px]"><div className="absolute -left-6 -top-7 -rotate-6 rounded-xl border-3 border-ink bg-white px-4 py-2 text-sm font-black shadow-sticker">1111 ARE HIDING 👀</div><div className="grid aspect-square grid-cols-3 gap-3 rounded-[2rem] border-4 border-ink bg-white/80 p-4 shadow-soft backdrop-blur-sm">{Array.from({length:9},(_,i)=><motion.div key={i} whileHover={{rotate:i%2?4:-4,scale:1.06}} animate={i===4?{y:[0,-7,0]}:{}} transition={i===4?{duration:2.4,repeat:Infinity}:undefined} className={`${colors[i%colors.length]} relative flex items-center justify-center rounded-2xl border-3 border-ink shadow-sticker`}><span className="text-4xl font-black">{i===4?'T':i%3===0?'?':'✦'}</span><span className="absolute bottom-2 left-3 text-[9px] font-black">#{String([1,111,222,333,555,777,888,999,1111][i]).padStart(4,'0')}</span>{i===1&&<span className="absolute right-3 top-3 text-lg">눈</span>}</motion.div>)}</div><p className="mt-5 text-center text-xs font-black tracking-[.15em]">곧 공개됩니다 · REVEAL LATER</p></div>}
