"use client";

import {FormEvent,useState} from "react";
import {ArrowDown,ArrowUpRight,Check,ChevronDown,ChevronRight,Gift,Home,Link2} from "lucide-react";
import {siteConfig} from "@/lib/site-config";

type Stage="home"|"tasks"|"form"|"share"|"done";
type Session={applicationId:string;tileNumber:number};

export function WhitelistJourney(){
 const[stage,setStage]=useState<Stage>("home");
 const[checks,setChecks]=useState([false,false,false,false]);
 const[session,setSession]=useState<Session|null>(null);
 const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const allDone=checks.every(Boolean);const toggle=(i:number)=>setChecks(v=>v.map((x,n)=>n===i?!x:x));
 async function apply(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const f=new FormData(e.currentTarget);try{const r=await fetch('/api/whitelist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({x_username:f.get('x_username'),wallet_address:f.get('wallet_address'),tasks_confirmed:allDone})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Application failed.');setSession({applicationId:j.applicationId,tileNumber:j.tileNumber});setStage('share')}catch(e){setError(e instanceof Error?e.message:'Application failed.')}finally{setLoading(false)}}
 async function verify(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!session)return;setLoading(true);setError("");const url=String(new FormData(e.currentTarget).get('x_post_url')||'');try{const r=await fetch('/api/whitelist/verify-x',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({applicationId:session.applicationId,xPostUrl:url})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Verification failed.');setStage('done')}catch(e){setError(e instanceof Error?e.message:'Verification failed.')}finally{setLoading(false)}}
 const shareText=siteConfig.createSignalPost();const intent=`https://x.com/intent/post?text=${encodeURIComponent(shareText)}`;
 return <main className="tile-site">
  <nav className="nav"><button className="brand" onClick={()=>setStage('home')}><span className="brand-mark">✿</span><span>TILE<small>타일 · 1111</small></span></button><div className="nav-links"><a href="#home">HOME</a><a href="#story">ABOUT</a><a href="#collection">COLLECTION</a><a href="#journey">ROADMAP</a><a href="#faq">FAQ</a><button className="nav-wl" onClick={()=>setStage('tasks')}>JOIN WHITELIST</button></div></nav>
  {stage==='home'?<>
   <section id="home" className="hero"><div className="hero-film"/><div className="hero-copy"><div className="hero-emblem">✿</div><h1>TILE</h1><p className="hero-line">THE ROOF THAT PROTECTS.<br/>THE COMMUNITY THAT BUILDS.</p><div className="hero-stats"><div><Home/><b>1,111</b><span>EXCLUSIVE<br/>COLLECTION</span></div><div><Link2/><b>MINT ON</b><span>ROBINHOOD CHAIN<br/>MAINNET</span></div><div><span className="giwa-g">G</span><b>MOVE TO GIWA</b><span>WHEN GIWA<br/>MAINNET IS LIVE</span></div><div><Gift/><b>GIWA REWARDS</b><span>REWARDS FOR<br/>TILE HOLDERS</span></div></div><div className="hero-actions"><button className="hero-cta primary" onClick={()=>setStage('tasks')}>JOIN WHITELIST <ArrowUpRight size={18}/></button><a className="hero-cta secondary" href="#story">LEARN MORE <ChevronDown size={18}/></a></div></div><div className="scroll-cue"><span>SCROLL TO DISCOVER</span><ArrowDown size={18}/></div><div className="side-rail"><b>01</b><span/><i>02</i><i>03</i><i>04</i><i>05</i></div></section>
   <section id="story" className="story-section"><div className="story-copy"><p className="eyebrow dark">WHAT IS TILE? · 타일이란?</p><h2>ONE TILE.<br/>ONE STORY.</h2><p>In Korean architecture, <b>giwa (기와)</b> are the traditional roof tiles that protect and shape a hanok. One tile can look small on its own. Together, they create a roof built to endure.</p><p><b>TILE is built on the same idea.</b> 1,111 individual pieces. Each different. Each part of something bigger.</p><blockquote>한 장의 기와가 모여 하나의 지붕을 만든다.<small>One tile becomes part of something greater.</small></blockquote></div><div className="story-card"><div className="giwa-object"><span>✿</span></div><div><p className="eyebrow dark">GIWA · 기와</p><h3>PROTECTING WHAT MATTERS.<br/>BUILDING WHAT&apos;S NEXT.</h3></div></div></section>
   <section id="collection" className="collection-grid"><article><p className="eyebrow">1,111 EXCLUSIVE COLLECTION</p><h3>Each one, a piece of culture.</h3><p>1,111 different TILEs inspired by the forms, rhythm and symbolism of Korean roof tiles.</p><button onClick={()=>setStage('tasks')}>JOIN WHITELIST <ChevronRight size={16}/></button></article><article><p className="eyebrow">GIWA REWARDS</p><h3>TILE holders will be rewarded on GIWA.</h3><p>TILE will mint first on Robinhood Chain mainnet. When GIWA mainnet goes live, the collection is planned to move to GIWA, where TILE holders will receive rewards.</p><a href={siteConfig.xUrl} target="_blank" rel="noreferrer">FOLLOW THE JOURNEY <ArrowUpRight size={16}/></a></article></section>
   <section id="journey" className="journey"><p className="eyebrow">BUILT FOR THE NEXT CHAPTER · 여정</p><h2>ROBINHOOD CHAIN → GIWA</h2><div className="journey-track"><article><span>01</span><small>MINT</small><h3>Robinhood Chain Mainnet</h3><p>TILE launches here first. Mint date: TBA.</p></article><article><span>02</span><small>COLLECTION</small><h3>1,111 TILEs</h3><p>Each piece different. One cultural system.</p></article><article><span>03</span><small>MIGRATION</small><h3>Move to GIWA</h3><p>When GIWA mainnet is live, TILE is planned to move to GIWA.</p></article><article><span>04</span><small>GIWA REWARDS</small><h3>Holder Rewards</h3><p>TILE holders will be rewarded on GIWA.</p></article></div></section>
   <section id="faq" className="wl-banner"><div className="foundation-mark">✿</div><div><p className="eyebrow">BE PART OF THE FOUNDATION.</p><h2>THE ROOF IS BUILT<br/>ONE TILE AT A TIME.</h2><p>TILE is about culture, community and what comes next.</p></div><button onClick={()=>setStage('tasks')}>JOIN WHITELIST <ArrowUpRight/></button></section>
  </>:
  <section className="wl-experience"><div className="wl-backdrop"/><div className="wl-wrap"><button className="close-wl" onClick={()=>setStage('home')}>← BACK TO TILE</button><div className="wl-heading"><p className="eyebrow">TILE WHITELIST · 화이트리스트</p><h2>{stage==='tasks'?'COMPLETE THE SIGNAL':stage==='form'?'LEAVE YOUR MARK':stage==='share'?'SHARE TILE':'APPLICATION VERIFIED'}</h2><div className="wl-progress">{['TASKS','APPLY','SHARE','VERIFY'].map((x,i)=><span className={i<={tasks:0,form:1,share:2,done:3}[stage]?'active':''} key={x}>0{i+1} {x}</span>)}</div></div>
   {stage==='tasks'&&<div className="task-layout"><aside><p className="step">STEP 01 · 신호</p><h3>Earn your place under the roof.</h3><p>Complete the X tasks, then continue with your EVM wallet.</p><div className="seal-1111">1111<small>PIECES · ONE STORY</small></div></aside><div className="task-list">{[['FOLLOW @TileOnGIWA','Follow the official TILE account.',siteConfig.xUrl],['LIKE THE WL POST','Like the official whitelist announcement.',siteConfig.whitelistPostUrl],['REPOST THE WL POST','Repost the whitelist announcement.',siteConfig.whitelistPostUrl],['TAG 2 FRIENDS','Reply to the WL post and tag two friends.',siteConfig.whitelistPostUrl]].map(([title,desc,url],i)=><div className={`task ${checks[i]?'checked':''}`} key={title}><button className="task-check" onClick={()=>toggle(i)}>{checks[i]?<Check/>:String(i+1).padStart(2,'0')}</button><div><b>{title}</b><p>{desc}</p></div><a href={url==='#'?undefined:url} target={url==='#'?undefined:'_blank'} rel="noreferrer">{url==='#'?'SOON':'OPEN'} <ArrowUpRight size={14}/></a></div>)}<button disabled={!allDone} className="next-step" onClick={()=>setStage('form')}>CONTINUE APPLICATION <ChevronRight/></button></div></div>}
   {stage==='form'&&<form onSubmit={apply} className="application-layout"><aside><p className="step">STEP 02 · 신청</p><h3>Leave your mark.</h3><p>Enter your X username and EVM wallet address. Final whitelist selection stays with the TILE team.</p></aside><div className="application-form"><label>X USERNAME<input name="x_username" required pattern="@?[A-Za-z0-9_]+" placeholder="@username"/></label><label>EVM WALLET ADDRESS<input name="wallet_address" required pattern="0x[a-fA-F0-9]{40}" placeholder="0x…"/></label>{error&&<p className="error">{error}</p>}<button disabled={loading}>{loading?'SUBMITTING…':'SUBMIT & CONTINUE'} <ChevronRight/></button></div></form>}
   {stage==='share'&&session&&<div className="share-layout"><aside><p className="step">STEP 03 · 공유</p><h3>Carry TILE outside.</h3><p>Share the prepared X post, return here and paste your post URL to finish verification.</p></aside><div className="share-panel"><pre>{shareText}</pre><a className="share-button" href={intent} target="_blank" rel="noreferrer">SHARE ON X <ArrowUpRight/></a><form onSubmit={verify}><label>YOUR X POST LINK<input name="x_post_url" required type="url" placeholder="https://x.com/username/status/..."/></label>{error&&<p className="error">{error}</p>}<button disabled={loading}>{loading?'VERIFYING…':'VERIFY & COMPLETE'} <Check/></button></form></div></div>}
   {stage==='done'&&<div className="verified"><div className="verified-mark"><Check/></div><p className="eyebrow">확인 완료 · VERIFIED</p><h3>YOU&apos;RE IN THE RECORD.</h3><p>Your TILE whitelist application has been verified.</p><small>Verification does not guarantee final whitelist allocation. Final selection is made by the TILE team.</small><button onClick={()=>setStage('home')}>RETURN TO TILE</button></div>}
  </div></section>}
 </main>
}
