"use client";
import {useEffect,useState} from "react";import {GiwaGame} from "@/components/GiwaGame";import {WhitelistForm} from "@/components/WhitelistForm";import {WhitelistProgress} from "@/components/WhitelistProgress";import {XSignal} from "@/components/XSignal";import {SignalVerified} from "@/components/SignalVerified";
type Stage="game"|"application"|"signal"|"verified";type Session={applicationId:string;tileNumber:number};
export function WhitelistJourney(){const[stage,setStage]=useState<Stage>("game");const[token,setToken]=useState("");const[session,setSession]=useState<Session|null>(null);const[ready,setReady]=useState(false);
useEffect(()=>{const savedSession=sessionStorage.getItem("tile_application_session");const savedStage=sessionStorage.getItem("tile_journey_stage") as Stage|null;const savedToken=sessionStorage.getItem("tile_assembly_token")||"";if(savedSession){try{setSession(JSON.parse(savedSession))}catch{sessionStorage.removeItem("tile_application_session")}}if(savedToken){setToken(savedToken);if(!savedStage||savedStage==='game')setStage('application')}if(savedStage==='application'||savedStage==='signal'||savedStage==='verified')setStage(savedStage);setReady(true)},[]);
function gameComplete(nextToken:string){setToken(nextToken);setStage('application');sessionStorage.setItem('tile_journey_stage','application')}
function submitted(applicationId:string,tileNumber:number){const next={applicationId,tileNumber};setSession(next);setStage('signal');sessionStorage.setItem('tile_application_session',JSON.stringify(next));sessionStorage.setItem('tile_journey_stage','signal')}
if(!ready)return <section id="whitelist" className="border-b-4 border-ink bg-pink/10"><div className="section text-center font-black">LOADING WL…</div></section>;
const active={game:0,application:1,signal:2,verified:3}[stage];return <section id="whitelist" className="relative overflow-hidden border-b-4 border-ink bg-pink/10"><div className="absolute -left-16 top-20 h-44 w-44 rounded-full bg-yellow/60 blur-3xl"/><div className="absolute -right-12 bottom-10 h-56 w-56 rounded-full bg-blue/40 blur-3xl"/><div className="section relative z-10"><div className="mx-auto max-w-5xl"><div className="mb-10 text-center"><span className="inline-block -rotate-2 rounded-full border-2 border-ink bg-mint px-4 py-2 text-xs font-black shadow-sticker">WL OPEN · 화이트리스트</span><h2 className="mt-6 text-5xl font-black tracking-[-.06em] sm:text-7xl">GET YOUR TILE.</h2><p className="mx-auto mt-4 max-w-xl text-base font-bold text-steel">Play the GIWA mini-game, apply for WL, post your TILE signal on X, then paste the post link back here to verify your request.</p></div><WhitelistProgress active={active}/><div className="mt-10 rounded-[2rem] border-4 border-ink bg-cream p-5 shadow-soft sm:p-8">{stage==='game'&&<GiwaGame onComplete={gameComplete}/>} {stage==='application'&&token&&<WhitelistForm assemblyToken={token} onSubmitted={submitted}/>} {stage==='signal'&&session&&<XSignal {...session} onVerified={()=>{setStage('verified');sessionStorage.setItem('tile_journey_stage','verified')}}/>}{stage==='verified'&&session&&<SignalVerified tileNumber={session.tileNumber}/>}</div></div></div></section>}
